### ISSUE TITLE
Collection Mechanism doesn't work.

### ISSUE THREAD

**Issue by KentaYanagi** [KentaYanagi/2022_SSSRC_CanSatA#1]
### Possible Cause:
code breakage

### Solution:
Inspect the disconnection point using a voltage tester

### Improvement Plan:
Created a guide to identify disconnection points in preparation for the main test

**Comment by shinikakenotoshiyori** [comment]
問題点：
電池のプラス側が電池ボックスの端子と接触しない。

原因：
本来、マイナス端子側のバネが電池を押すので、電池が電池ボックスの両方の端子に接触するのだが、私たちが購入した電池ボックスは細すぎるため、電池が側面で挟まってしまい、バネが押すことが出来なかったことが原因と考えられる。

解決策：
手で押したり入れなおしたりすればつながるので、ちゃんと確認することが重要である。
